"""Executable consumer examples generated by the real service, never fabricated success."""
import json
import tempfile
from pathlib import Path
from uuid import NAMESPACE_URL,uuid5
from unittest.mock import patch
from safina.domain import ROOT,REF,RULE_VERSION,instant
from safina.service import Service
from safina.store import Store

B=[{'start':'2:1','end':'2:286'}]
class Fixtures:
    def __init__(self,store):
        self.now=instant('2026-10-01T12:00:00+10:00');self.s=Service(store,now=lambda:self.now,signing_key=b'fixture-only-not-a-server-secret');self.n=0
    def uuid(self):
        self.n+=1;return str(uuid5(NAMESPACE_URL,'safina-fixture-'+str(self.n)))
    def member(self,name,tier,start='2026-09-01'):
        self.s.provision(name,tier,'Australia/Brisbane',start)
    def body(self,member,day,ranges=B,**kwargs):
        a=self.s.today(member,day)['assignment']
        return {'mutationId':self.uuid(),'logicalActId':self.uuid(),'occurrenceDate':day,'occurredAt':day+'T09:00:00+10:00',
                'timezone':'Australia/Brisbane','utcOffsetMinutes':600,'ranges':ranges,'source':'manual_physical',
                'assignmentId':a['id'],'ruleVersion':RULE_VERSION,'referenceVersion':REF.version,**kwargs}
    def write(self,name,schema,data):
        (ROOT/'contracts/fixtures'/f'{name}.json').write_text(json.dumps({'schema':schema,'contractVersion':'0.3.0','fixture':data},ensure_ascii=False,indent=2)+'\n')
    def run(self):
        for tier in ('B','BI','BJ1','BJ2','BJ3','BJ4','BJ5'):
            self.member(tier,tier);day='2026-09-01' if tier=='BJ2' else '2026-09-16'
            self.write('today-'+tier,'Today',self.s.today(tier,day))
        req=self.body('BJ2','2026-09-01');self.write('reading-request','ReadingCreate',req)
        result=self.s.mutate('BJ2','reading',req);self.write('bj2-day-one','ReadingMutationResult',result)
        self.write('program-rules','RuleRegistry',json.loads((ROOT/'data/program_rules.json').read_text()))
        self.s.mutate('BJ3','reading',self.body('BJ3','2026-09-16'))
        self.now=instant('2026-09-16T14:00:00+10:00')
        c=self.s._commitment_at(self.s.state('BJ3'),self.now)
        self.s.mutate('BJ3','change',{'mutationId':self.uuid(),'tier':'BJ1','expectedCommitmentId':c['id'],'ruleVersion':RULE_VERSION})
        self.write('bj1-day16-switch','Today',self.s.today('BJ3','2026-09-16'))
        self.now=instant('2026-10-01T12:00:00+10:00')
        self.s.mutate('BJ5','reading',self.body('BJ5','2026-09-12'))
        self.write('bj5-sunday-reset','Today',self.s.today('BJ5','2026-09-13'))
        self.member('ship','B')
        for d in range(1,31):self.s.mutate('ship','reading',self.body('ship',f'2026-09-{d:02d}'))
        self.write('b-only-ship','ShipProgress',self.s.ship('ship'))
        self.write('b-only-khatmas','Khatmas',self.s.khatmas('ship'))
        self.member('reader','B');tid=self.uuid()
        self.s.mutate('reader','trace',{'mutationId':self.uuid(),'expectedRevision':0,'occurrenceDate':'2026-09-01','occurredAt':'2026-09-01T09:00:00+10:00','timezone':'Australia/Brisbane','utcOffsetMinutes':600,'observations':[{'kind':'exposed','ranges':B}],'referenceVersion':REF.version},tid)
        self.write('reader-suggestion','TraceResult',self.s.trace('reader',tid))
        r=self.s.mutate('reader','reading',self.body('reader','2026-09-01',[{'start':'2:1','end':'2:141'}],source='reader_confirmed',traceId=tid))
        self.write('reader-shortened-confirmation','ReadingMutationResult',r)
        a=r['act'];r=self.s.mutate('reader','correct',{'mutationId':self.uuid(),'expectedRevision':1,'reason':'Corrected my reported endpoint','ranges':[{'start':'2:1','end':'2:100'}],'ruleVersion':RULE_VERSION,'referenceVersion':REF.version},a['id'])
        self.write('reader-correction','ReadingMutationResult',r)
        self.write('calendar','Calendar',self.s.calendar('reader','2026-09-01','2026-09-03'))
        self.write('day-evaluation','DayEvaluation',self.s.day('reader','2026-09-01'))
        self.write('offline-snapshot','OfflineSnapshot',self.s.offline_snapshot('reader','2026-09-01'))
        self.member('free','BJ1','2026-08-01');self.write('monthly-free-day','Today',self.s.today('free','2026-08-31'))
        self.member('feb','BJ1','2026-02-01');self.write('february-awaiting-policy','Today',self.s.today('feb','2026-02-28'))
        self.write('bj2-day-two-awaiting-policy','Today',self.s.today('BJ2','2026-09-02'))
        self.write('bj5-saturday-free','Today',self.s.today('BJ5','2026-09-12'))

if __name__=='__main__':
    with tempfile.TemporaryDirectory() as d:
        store=Store(Path(d)/'fixtures.db');f=Fixtures(store)
        with patch('safina.service.uuid4',side_effect=f.uuid):f.run()
        store.close()
    print('Generated real-service consumer fixtures for all seven tiers and founder review scenarios.')
